version: "3.8"

volumes:
  postgres_db_vol_newzealidar:

services:

  postgres:
    image: postgis/postgis
    container_name: lidar-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_db_vol_newzealidar:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -h 127.0.0.1 -U $POSTGRES_USER -d $POSTGRES_DB
